name: app_a' production

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main


jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/_tf_plan.yml
    with:
      workspace: 'app_a/production'
      aws_region: 'ap-northeast-1'
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}