name: app_a' production

on:
  workflow_dispatch:
  push:
    paths:
      - 'app_a/production/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  tf_plan_iam:
    uses: ./.github/workflows/_tf_plan.yml
    with:
      workspace: 'app_a/production/iam'
      aws_region: 'ap-northeast-1'
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}

  tf_plan_vpc:
    uses: ./.github/workflows/_tf_plan.yml
    with:
      workspace: 'app_a/production/vpc'
      aws_region: 'ap-northeast-1'
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}